name: fly.io Destroy
on:
  pull_request_target:
    branches: [ main ]
    types: [unlabeled, closed]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  destroy:
    name: Remove app from fly.io
    runs-on: ubuntu-latest
    # Remove the deployment when 'preview' label is removed, or the PR is closed.
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request_target' &&
      (github.event.action == 'closed' ||
      (github.event.action == 'unlabeled' && github.event.label.name == 'preview')))
    steps:
      - uses: actions/checkout@v4
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.2.72
      - name: Destroy fly.io app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          BRANCH_NAME: ${{ github.event.pull_request_target.base_ref }}
        id: fly_destroy
        run: node buildtools/fly-deploy.js destroy
